# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /Users/labadier/projects/play/HateBot_Kuber/host_mounting_points/kind_node_0
        containerPath: /some/path/in/container
  - role: worker
    extraMounts:
      - hostPath: /Users/labadier/projects/play/HateBot_Kuber/host_mounting_points/kind_node_1
        containerPath: /some/path/in/container
  - role: worker
    extraMounts:
      - hostPath: /Users/labadier/projects/play/HateBot_Kuber/host_mounting_points/kind_node_2
        containerPath: /some/path/in/container
  