apiVersion: v1
kind: Pod
metadata:
  name: mlflow-server
  namespace: hatebot
  labels:
    app: mlflow
  
spec:
  containers:
    - name: mlflow
      image: ghcr.io/mlflow/mlflow
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow:8080
      command: ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow/mlruns/mlflow.db", "--default-artifact-root", "/mlflow/mlruns", "--host", "0.0.0.0", "--port", "8080"] 
      volumeMounts:
        - name: mlflow-volume
          mountPath: /mlflow/mlruns 

      # readinessProbe:        # I always recommend using these, even if your app has no listening ports (this affects any rolling update)
      #   httpGet:             # Lots of timeout values with defaults, be sure they are ideal for your workload
      #     path: http://mlflow/
      #     port: 8080
      # livenessProbe:         # only needed if your app tends to go unresponsive or you don't have a readinessProbe, but this is up for debate
      #   httpGet:             # Lots of timeout values with defaults, be sure they are ideal for your workload
      #     path: http://mlflow/
      #     port: 8080

      # resources:             # Because if limits = requests then QoS is set to "Guaranteed"
      #   limits:
      #     memory: "1000Mi"    # If container uses over 500MB it is killed (OOM)
      #     cpu: "2"          # Not normally needed, unless you need to protect other workloads or QoS must be "Guaranteed"
      #   requests:
      #     memory: "500Mi"    # Scheduler finds a node where 500MB is available
      #     cpu: "1"           # Scheduler finds a node where 1 vCPU is available

      # per-container security context
      # lock down privileges inside the container
      # securityContext:
      #   allowPrivilegeEscalation: false # prevent sudo, etc.
      #   privileged: false               # prevent acting like host root


  # terminationGracePeriodSeconds: 600 # default is 30, but you may need more time to gracefully shutdown (HTTP long polling, user uploads, etc)

  volumes:
    - name: mlflow-volume
      hostPath: 
        path: /mnt/mlflow/mlruns # this is the host path, not the container path
        type: "" # this is the type of volume, not the path

  securityContext:

    seccompProfile:
      type: RuntimeDefault   

    runAsUser: 501          
    runAsGroup: 20       
    runAsNonRoot: true      