apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server-deployment
  namespace: hatebot
  labels:
    app: mlflow
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlflow-pods-server # This key, value pair must match the labels in the Pod template and may be arbitrary (both)
  template:
    metadata:
      labels:
        app: mlflow-pods-server
      annotations:
        gke-gcsfuse/volumes: "true"

    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:8080
          command: ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow/mlruns/mlflow.db", "--default-artifact-root", "/mlflow/mlruns", "--host", "0.0.0.0", "--port", "8080"] 
          volumeMounts:
            - name: mlflow-volume
              mountPath: /mlflow
              readOnly: false

      
      serviceAccountName: hatebot-service-account
      volumes:
        - name: mlflow-volume
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: mlruns-artifacts
              mountOptions: "implicit-dirs"
              objectPrefix: mlruns
          # hostPath: 
          #   path: /mnt/mlflow/mlruns # this is the host path, not the container path
          #   type: "" # this is the type of volume, not the path

      securityContext: {}

      #   seccompProfile:
      #     type: RuntimeDefault   

        # runAsUser: 501          
        # runAsGroup: 20       
        # runAsNonRoot: true      