apiVersion: v1
kind: ServiceAccount
metadata:
  name: hatebot-service-account
  namespace: hatebot


### To mount buckets this must be annotated to the GSA
# kubectl annotate serviceaccount hatebot-service-account \
#   --namespace hatebot \
#   iam.gke.io/gcp-service-account=hatebot-service-account@kubernetes-course-455312.iam.gserviceaccount.com \
#   --overwrite