apiVersion: v1
kind: Service
metadata:
  name: inference-loadbalancer
  namespace: hatebot
  labels:
    app: inference-loadbalancer

spec:
  type: LoadBalancer  
  selector:
    app: inference-server-pod  
  ports:
    - protocol: TCP
      port: 8080   # Exposed service port
      targetPort: 8082  # Pod port (same as in the Pod definition)