apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: hatebot

spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if you want external access
  selector:
    app: mlflow-pods-server  # Ensure this matches the label of your MLflow Pod
  ports:
    - protocol: TCP
      port: 8080   # Exposed service port
      targetPort: 8080  # Pod port (same as in the Pod definition)
  clusterIP: None  # Optional: this makes the service headless, meaning DNS resolution will go directly to Pods